build:
  stage: build
  image:
    # name: busybox
    name: gcr.io/kaniko-project/executor:debug
    # entrypoint: ["ls"]
  tags:
    - docker
  # before_script:
  #   - cert=$(cat ca.crt)
  #   - echo "$cert" >> /kaniko/ssl/certs/ca-certificates.crt
  #   - echo $(cat docker_ca.crt) >> /kaniko/ssl/certs/ca-certificates.crt
  script:
    echo "hello world"
    - /kaniko/executor
      # --insecure-pull
      # --insecure-registry 192.168.200.138:5000
      --destination "busybox:0.0.1"
      --context 
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"

  # rules:
  #   - if: $CI_COMMIT_TAG
    