build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  tags:
    - docker
  before_script:
    - cert=$(cat ca.crt)
    - echo "$cert" > /kaniko/ssl/certs/ca-certificates.crt
  script:
    - cat /kaniko/ssl/certs/ca-certificates.crt
    # - /kaniko/executor
    #   --context "${CI_PROJECT_DIR}"
    #   --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
    #   --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  # rules:
  #   - if: $CI_COMMIT_TAG
    