version: '3.6'
services:
  db:
    image: ${REGISTRY}/ironbank/tpc/tak/tak-server-db:${RELEASE_TAG}
    ports:
      - 5432:5432
    volumes:
      - ./app:/app
    environment:
      - envpass=${DB_PASS}
  server:
    image: ${REGISTRY}/ironbank/tpc/tak/tak-server:${RELEASE_TAG}
    ports:
      - 8080:80
    volumes:
      - ./app:/app
    environment:
      - ENV_VARIABLE=value
  hub:
    image: ${REGISTRY}/ironbank/tpc/tak/tak-server-fedhub:${RELEASE_TAG}
    ports:
      - 8080:80
    volumes:
      - ./app:/app
    environment:
      - ENV_VARIABLE=value
  ca:
    image: ${REGISTRY}/ironbank/tpc/tak/tak-server-fedhub:${RELEASE_TAG}
    ports:
      - 8080:80
    volumes:
      - ./app:/app
    environment:
      - ENV_VARIABLE=value

networks:
  tak_network:


